import type { ActionLibraryItem } from "@mentis/domain";

/**
 * 人工编写的膝关节康复种子库。
 *
 * 每条动作的 `actionType` + `targetMuscles` 是复用的前提：Task 7 的
 * `isLibraryActionMatch` 会拿模型声明的动作类型/目标肌群和库里的这两个字段比对，
 * 缺一个就永远判不匹配、这条动作等于不存在。
 *
 * `bodyRegions` 必须列全动作真正跨到的关节（腘绳肌拉伸同时属于 knee 和 hip）——
 * 单归属正是「病人说膝后紧、系统却推股四头肌拉伸」那次错配的根源。
 */
export const kneeRehabActionLibrary: ActionLibraryItem[] = [
  // ---------------------------------------------------------------------------
  // 镇痛与激活
  // ---------------------------------------------------------------------------
  {
    id: "action_quad_iso",
    title: "股四头肌等长收缩",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "activation",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 10 次，每次保持 5 秒，组间休息 30 秒",
    instructions: [
      "仰卧或长坐，患侧腿伸直放平，脚尖朝上，膝下不要垫枕头",
      "缓慢绷紧大腿前侧，像要把膝盖后方压向床面，同时脚跟会略微离床",
      "正确的感觉是大腿前侧变硬、髌骨被向上拉，膝关节本身不应出现刺痛",
      "保持 5 秒，正常呼吸不要憋气，再用 3 秒缓慢放松",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝关节明显肿胀发热时先冰敷抬高，不要强行加练",
    ],
    progressionCriteria: [
      "可连续完成 3 组 x 10 次且收缩时无膝前痛",
      "训练后 24 小时内肿胀与疼痛无反跳",
    ],
    tags: ["膝盖", "等长收缩", "低刺激", "术后早期"],
  },
  {
    id: "action_straight_leg_raise",
    title: "直腿抬高",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "activation",
    targetMuscles: ["股四头肌", "髂腰肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 10 次，每次抬起后保持 2 秒",
    instructions: [
      "仰卧，健侧腿屈膝踩地稳定骨盆，患侧腿完全伸直",
      "先绷紧患侧大腿前侧把膝盖锁直，确认膝盖不会弯再开始抬腿",
      "保持膝盖伸直，把整条腿抬到约 30-40 厘米（与健侧大腿平齐即可）",
      "顶端停 2 秒，再用 3 秒缓慢放下，全程腰部不要拱起离床",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "抬腿时膝盖出现「伸不直的下垂」（伸膝迟滞）说明力量不足，先退回股四头肌等长收缩",
      "出现腰痛或腿部放射痛立即停止",
    ],
    progressionCriteria: [
      "全程膝关节无伸膝迟滞，能连续完成 3 组 x 10 次",
      "可在踝部加 1-2 kg 沙袋仍保持膝盖锁直",
    ],
    tags: ["膝盖", "激活", "股四头肌", "术后早期"],
  },
  {
    id: "action_ankle_pump",
    title: "踝泵",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "activation",
    targetMuscles: ["小腿三头肌", "胫骨前肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "每小时 1 组，每组 20 次，勾脚与绷脚各保持 2 秒",
    instructions: [
      "仰卧或坐位，患侧腿伸直，小腿放松",
      "用力勾脚尖朝向自己，感到小腿后侧被拉紧，保持 2 秒",
      "再用力绷脚尖向下踩，感到小腿后侧收紧，保持 2 秒",
      "动作缓慢有节奏，只有踝关节在动，膝盖保持不动",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "小腿突发胀痛、发红发热并伴局部压痛，警惕深静脉血栓，立即停止并就医",
    ],
    progressionCriteria: [
      "可无痛连续完成 20 次，踝关节活动到底不受限",
      "小腿与踝部肿胀较前减轻",
    ],
    tags: ["膝盖", "踝泵", "消肿", "术后早期"],
  },
  {
    id: "action_glute_set",
    title: "臀肌等长收缩",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "activation",
    targetMuscles: ["臀大肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 10 次，每次保持 5 秒",
    instructions: [
      "仰卧或俯卧，双腿自然伸直，膝盖放松不发力",
      "夹紧臀部肌肉，像把两侧臀部向中间挤，臀部会轻微抬离床面一点点",
      "正确的感觉是臀部变硬，大腿后侧和腰部不应抽筋或发酸",
      "保持 5 秒后完全放松 3 秒，再重复",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "出现腰部挤压痛说明用腰代偿，先减小收缩力度",
    ],
    progressionCriteria: [
      "能单独收缩臀部而不靠腰或大腿后侧代偿",
      "可连续完成 3 组 x 10 次无不适",
    ],
    tags: ["膝盖", "臀肌激活", "低刺激", "术后早期"],
  },
  {
    id: "action_quad_over_towel",
    title: "毛巾下压伸膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "activation",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 10 次，每次保持 5-10 秒",
    instructions: [
      "长坐或仰卧，把一条卷起的毛巾垫在患侧膝关节下方，脚跟悬空",
      "绷紧大腿前侧，用膝盖后方向下压毛巾，让脚跟随之抬起、膝盖尽量伸直",
      "正确的感觉是大腿前侧发力、膝后有轻微牵拉，而不是膝盖里面刺痛",
      "保持 5-10 秒，缓慢放松让脚跟落回，再重复",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "医生对伸膝角度有限制（如后交叉或半月板缝合术后）时，先确认允许范围",
    ],
    progressionCriteria: [
      "脚跟可稳定抬离床面并保持 10 秒",
      "患侧被动伸直角度接近健侧（差距在 5 度以内）",
    ],
    tags: ["膝盖", "伸膝", "激活", "术后早期"],
  },
  {
    id: "action_heel_prop",
    title: "足跟垫高伸膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "mobility",
    targetMuscles: ["腘绳肌", "股四头肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "每次 5-10 分钟，每天 3-4 次",
    instructions: [
      "仰卧或半躺，把患侧足跟垫在毛巾卷或矮凳上，让小腿与大腿悬空",
      "大腿完全放松，靠腿本身的重量让膝关节慢慢向下沉、伸直",
      "正确的感觉是膝后有持续、可忍受的牵拉感，不是尖锐痛",
      "维持 5-10 分钟，可在大腿远端加一个轻沙袋增加牵伸",
      "结束后先屈伸膝盖几次再站起来",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "牵拉时出现小腿麻木或足部发凉，立即取下重物并停止",
      "有伸膝角度限制的术后患者需先获得医生许可",
    ],
    progressionCriteria: [
      "可在无痛下维持 10 分钟",
      "膝关节伸直角度较上周改善或已与健侧一致",
    ],
    tags: ["膝盖", "伸膝角度", "被动牵伸", "术后早期"],
  },
  {
    id: "action_short_arc_quad",
    title: "小弧度伸膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "activation",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 12 次，顶端保持 3 秒",
    instructions: [
      "仰卧，把一个直径约 20 厘米的泡沫轴或毛巾卷垫在患侧膝下，膝关节屈约 30 度",
      "保持大腿始终贴在支撑物上，只把小腿抬起，直到膝盖完全伸直",
      "顶端绷紧大腿前侧保持 3 秒，感觉膝盖上方的肌肉明显收紧",
      "用 3 秒缓慢把小腿放回，不要让它自由落下",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "髌骨前方出现摩擦痛或弹响伴疼痛时减小活动范围",
      "空手做无妨；但踝部加负荷属于抗阻开链伸膝，ACL 重建术后早中期须经医生/治疗师许可后再加",
    ],
    progressionCriteria: [
      "顶端可完全伸直并保持 3 秒无抖动",
      "可在踝部加 1-2 kg 负荷完成 3 组 x 12 次（ACL 术后须先获许可）",
    ],
    tags: ["膝盖", "伸膝", "股四头肌", "小范围"],
  },
  {
    id: "action_bridge",
    title: "臀桥",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "activation",
    targetMuscles: ["臀大肌", "腘绳肌"],
    source: "seed",
    phase: "镇痛与激活",
    defaultDosage: "3 组 x 12 次，顶端保持 2 秒",
    instructions: [
      "仰卧屈膝，双脚与髋同宽踩地，脚跟大约在膝盖正下方，双手放身体两侧",
      "先夹紧臀部，再用脚跟压地把髋部抬起，直到肩、髋、膝成一条斜线",
      "正确的感觉是臀部酸胀发力；如果只有大腿后侧发酸甚至抽筋，说明脚跟离臀太远，把脚往回收一点",
      "顶端保持 2 秒，再用 3 秒一节一节把背放回床面",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "顶端出现腰部挤压痛说明用腰代偿，降低抬起高度",
      "腘绳肌肌腱术后或急性拉伤期避免大范围屈膝发力",
    ],
    progressionCriteria: [
      "可完成 3 组 x 12 次且以臀部发力为主",
      "能进阶到双脚抬高或单腿臀桥而骨盆不侧倾",
    ],
    tags: ["膝盖", "臀肌激活", "髋伸", "闭链"],
  },

  // ---------------------------------------------------------------------------
  // 活动度与拉伸
  // ---------------------------------------------------------------------------
  {
    id: "action_heel_slide",
    title: "足跟滑动屈膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "mobility",
    // 屈膝 ROM 动作两块肌肉都要列：模型描述足跟滑动时可能说腘绳肌、也可能说股四头肌，
    // 匹配是 some()，只列一块就会永远失配、这条等于不存在。
    targetMuscles: ["股四头肌", "腘绳肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 10 次，每次在最大屈膝位保持 5 秒",
    instructions: [
      "仰卧，患侧腿伸直，脚下垫一块滑布或穿袜子踩在光滑地面上",
      "缓慢把足跟朝臀部方向滑动，让膝盖慢慢弯曲，可用毛巾套住足踝辅助拉",
      "滑到出现明显牵拉或轻微紧绷（不是刺痛）时停住，保持 5 秒",
      "再缓慢把腿滑回完全伸直位，每次尝试比上一次多弯一点点",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝关节出现卡住、交锁或突然打软，停止并联系医生",
      "半月板缝合术后早期屈膝角度须遵医嘱上限",
    ],
    progressionCriteria: [
      "屈膝角度每周有进展，或已达到 120 度以上",
      "滑动全程无卡顿、无明显疼痛",
    ],
    tags: ["膝盖", "屈膝角度", "主动辅助", "术后早期"],
  },
  {
    id: "action_prone_hang",
    title: "俯卧垂腿伸膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "mobility",
    targetMuscles: ["腘绳肌", "股四头肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "每次 5-10 分钟，每天 2-3 次",
    instructions: [
      "俯卧在床上，让患侧大腿远端到脚全部悬在床沿外，髌骨上缘刚好露出床边",
      "大腿和小腿彻底放松，让小腿的重量把膝关节向下拉直",
      "正确的感觉是膝后持续的牵拉感，越放松效果越好，不要用力对抗",
      "维持 5-10 分钟；可在踝部挂 1-2 kg 轻沙袋加强，但不应引起疼痛",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "出现小腿麻木、刺痛或足部发凉立即取下负荷并停止",
      "后交叉韧带术后须经医生许可后再做",
    ],
    progressionCriteria: [
      "患侧可完全伸直并与健侧对称",
      "可在无痛下维持 10 分钟",
    ],
    tags: ["膝盖", "伸膝角度", "重力牵伸"],
  },
  {
    id: "action_seated_hamstring_stretch",
    title: "坐姿腘绳肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["腘绳肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 30 秒，每天 1-2 次",
    instructions: [
      "坐在椅子前缘，患侧腿向前伸直，脚跟着地、脚尖勾起朝向自己",
      "另一条腿屈膝踩地，双手放在大腿上，腰背保持挺直",
      "以髋关节为轴、上身像门板一样整体前倾，不要弓背弯腰去够脚尖",
      "感到大腿后方从臀下到膝后的牵拉感即停住，保持 30 秒后缓慢回正",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "出现沿小腿向足部放射的麻木或电击感，说明牵到坐骨神经，立即停止",
      "腘绳肌急性拉伤 72 小时内不做拉伸",
    ],
    progressionCriteria: [
      "牵拉感可耐受、无放射症状，且日常屈髋伸膝时膝后紧绷感减轻",
      "同样姿势下前倾幅度较前增大或已与健侧对称",
    ],
    tags: ["膝盖", "拉伸", "腘绳肌", "膝后紧"],
  },
  {
    id: "action_supine_hamstring_strap",
    title: "仰卧弹力带腘绳肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["腘绳肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 30 秒，每天 1-2 次",
    instructions: [
      "仰卧，用弹力带或毛巾套住患侧足底，健侧腿屈膝踩地或伸直放平",
      "患侧膝盖尽量伸直，双手拉带把整条腿向上抬向天花板",
      "抬到大腿后方出现明显牵拉感即停，腰部始终贴地不要翘起",
      "保持 30 秒，其间正常呼吸；缓慢放下后休息 15 秒再做下一组",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "出现小腿或足底放射麻木、电击感立即降低抬腿高度并停止",
      "拉伸中膝盖被强行掰直引起膝前痛时，允许膝关节微屈 10-20 度",
    ],
    progressionCriteria: [
      "抬腿角度较前增加，或已能在膝直位抬到约 80 度",
      "拉伸后行走与上下楼时膝后紧绷感减轻",
    ],
    tags: ["膝盖", "拉伸", "腘绳肌", "弹力带"],
  },
  {
    id: "action_prone_quad_stretch",
    title: "俯卧股四头肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 30 秒，每侧",
    instructions: [
      "俯卧，双腿并拢，腹部微微收紧防止腰部塌陷",
      "屈曲患侧膝关节，用同侧手或弹力带勾住脚踝，把足跟拉向臀部",
      "正确的感觉是大腿前侧从髋到膝的牵拉，而不是膝盖里面被挤压的痛",
      "保持 30 秒，全程髋部贴床、膝盖不要向外打开",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "髌股关节疼痛或髌腱痛在深屈膝下加重时，减小屈膝角度或改做站姿版本",
      "屈膝角度受限的术后早期患者不做",
    ],
    progressionCriteria: [
      "足跟与臀部距离较前缩短，且无膝前痛",
      "两侧牵拉感对称",
    ],
    tags: ["膝盖", "拉伸", "股四头肌"],
  },
  {
    id: "action_standing_quad_stretch",
    title: "站姿股四头肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 30 秒，每侧",
    instructions: [
      "站立，一手扶墙或椅背保持稳定，重心放在健侧腿上",
      "屈曲患侧膝关节，同侧手抓住脚背把足跟拉向臀部，膝盖指向地面",
      "收紧臀部让骨盆略后倾，此时大腿前侧牵拉感会明显增强",
      "保持 30 秒，腰部不要塌陷、两膝保持并拢，再缓慢放下",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "平衡差或有跌倒风险时必须扶稳，或改为俯卧位拉伸",
      "深屈膝引发髌骨前方疼痛时减小幅度",
    ],
    progressionCriteria: [
      "可无扶持完成并保持 30 秒",
      "足跟能贴近臀部且大腿前侧无痛",
    ],
    tags: ["膝盖", "拉伸", "股四头肌", "站姿"],
  },
  {
    id: "action_gastroc_stretch",
    title: "站姿腓肠肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "stretch",
    targetMuscles: ["小腿三头肌", "腓肠肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "负重限制解除后再做：3 组 x 30 秒，每侧",
    instructions: [
      "面对墙站立，双手扶墙，患侧腿在后、健侧腿在前呈弓步",
      "后腿膝盖完全伸直，脚尖朝前，脚跟始终踩实地面",
      "身体重心缓慢前移，直到后侧小腿上半部出现明显牵拉感",
      "保持 30 秒，不要弹震，牵拉感应在小腿肚而不是跟腱止点或膝后",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跟腱急性损伤或跟腱修复术后早期禁用",
      "本动作由患侧腿在后承重、脚跟压地：术后负重限制未解除前不做，改为坐位或仰卧用毛巾勾脚牵拉",
      "牵拉时膝后出现尖锐痛应停止并减小前移幅度",
      "小腿突发胀痛、发红发热并伴局部压痛，警惕深静脉血栓，立即停止并就医",
    ],
    progressionCriteria: [
      "踝背屈角度较前增大，下蹲时脚跟更容易踩实",
      "牵拉时无跟腱疼痛",
    ],
    tags: ["膝盖", "拉伸", "小腿", "踝背屈"],
  },
  {
    id: "action_soleus_stretch",
    title: "站姿比目鱼肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "stretch",
    targetMuscles: ["小腿三头肌", "比目鱼肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "负重限制解除后再做：3 组 x 30 秒，每侧",
    instructions: [
      "面对墙弓步站立，患侧腿在后、脚跟踩实",
      "与腓肠肌拉伸不同：后腿膝盖要略微弯曲（约 20-30 度）",
      "保持脚跟不离地，重心下沉并前移，牵拉感应出现在小腿下段靠近跟腱处",
      "保持 30 秒，缓慢起身，换边或重复",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跟腱急性疼痛期或跟腱术后早期禁用",
      "本动作由患侧腿在后屈膝承重：术后负重限制未解除前不做，改为坐位屈膝用毛巾勾脚牵拉",
      "脚跟一旦离地即为代偿，应减小幅度而不是硬压",
      "小腿突发胀痛、发红发热并伴局部压痛，警惕深静脉血栓，立即停止并就医",
    ],
    progressionCriteria: [
      "屈膝位踝背屈角度增大，下蹲时躯干更容易保持直立",
      "牵拉后小腿下段紧绷感减轻",
    ],
    tags: ["膝盖", "拉伸", "比目鱼肌", "踝背屈"],
  },
  {
    id: "action_itb_stretch",
    title: "髂胫束拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["阔筋膜张肌", "髂胫束"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 30 秒，每侧",
    instructions: [
      "站立扶墙，患侧腿交叉到健侧腿后方，两脚踩实",
      "髋部朝健侧方向缓慢推出，同侧手臂可上举越过头顶向对侧侧屈",
      "牵拉感应出现在患侧髋外侧和大腿外侧，而不是腰部或膝盖外侧关节线",
      "保持 30 秒，缓慢回正，换边或重复",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝外侧关节线出现刺痛（可能为外侧半月板问题）时停止",
      "髋外侧滑囊炎急性期避免加压牵拉",
    ],
    progressionCriteria: [
      "跑步或下楼后膝外侧摩擦痛减轻",
      "同样姿势下髋外侧牵拉幅度增大",
    ],
    tags: ["膝盖", "拉伸", "髂胫束", "膝外侧痛"],
  },
  {
    id: "action_hip_flexor_stretch",
    title: "半跪位髂腰肌拉伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "stretch",
    targetMuscles: ["髂腰肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "负重限制解除后再做：3 组 x 30 秒，每侧",
    instructions: [
      "半跪位，患侧膝盖跪在软垫上，健侧腿在前屈髋屈膝约 90 度",
      "先收紧臀部让骨盆后倾（尾骨向前卷），此时大腿根前方就应有牵拉感",
      "保持骨盆后倾，重心缓慢前移，不要靠塌腰去加大幅度",
      "保持 30 秒；跪地不适可在膝下加厚垫，或改为站姿弓步版本",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跪姿膝前受压疼痛（髌骨挫伤、髌腱炎、膝前手术切口未愈）时改站姿版本",
      "出现腰部挤压痛说明骨盆没后倾，先纠正姿势",
    ],
    progressionCriteria: [
      "站立与行走时骨盆前倾/腰椎前凸减轻",
      "同样姿势下牵拉感减弱，可增加前移幅度",
    ],
    tags: ["膝盖", "拉伸", "髋屈肌", "半跪"],
  },
  {
    id: "action_calf_wall_stretch",
    title: "靠墙小腿拉伸（患侧负重）",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "stretch",
    targetMuscles: ["小腿三头肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "负重限制解除后再做：3 组 x 30 秒，每侧",
    instructions: [
      "面对墙站立，把患侧前脚掌踩在墙面上，脚跟留在地面，形成脚背上翘的角度",
      "另一条腿在后支撑，双手扶墙",
      "身体缓慢向墙靠近，直到小腿后方与足底出现牵拉感",
      "保持 30 秒，缓慢退回，两侧各做 3 组",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跟腱或足底筋膜急性疼痛期减小角度、避免弹震",
      "本动作为站立位患侧承重：术后负重限制未解除前不做，改为坐位用毛巾勾脚牵拉",
      "小腿突发胀痛伴发红发热应警惕血栓，立即停止并就医",
    ],
    progressionCriteria: [
      "踝背屈活动度增大，步行时推蹬更顺畅",
      "拉伸后晨起足底或小腿僵硬感减轻",
    ],
    tags: ["膝盖", "拉伸", "小腿", "靠墙"],
  },
  {
    id: "action_patellar_mobilization",
    title: "髌骨松动",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "mobility",
    targetMuscles: ["髌周软组织", "股四头肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "每个方向 10 次，每次保持 5-10 秒，每天 2-3 次",
    instructions: [
      "长坐，患侧腿伸直放松，膝下可垫薄毛巾；大腿必须完全放松，否则髌骨推不动",
      "用拇指和食指捏住髌骨边缘，先把髌骨缓慢推向内侧到有紧绷感，保持 5-10 秒",
      "再依次向外侧、上方、下方各推动并保持，动作轻柔、不要用力撬",
      "全程只应有轻微牵拉或紧绷感，不应出现刺痛或摩擦性疼痛",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "有髌骨脱位或半脱位史者不做向外侧推动",
      "切口未愈合、局部皮肤感染或明显肿胀时暂缓",
    ],
    progressionCriteria: [
      "髌骨四个方向活动度较前改善且左右接近对称",
      "屈膝与伸膝活动时髌骨周围紧绷感减轻",
    ],
    tags: ["膝盖", "髌骨", "关节松动", "术后早期"],
  },
  {
    id: "action_seated_knee_flexion",
    title: "坐姿主动屈膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "mobility",
    targetMuscles: ["腘绳肌"],
    source: "seed",
    phase: "活动度与拉伸",
    defaultDosage: "3 组 x 10 次，每次在最大屈膝位保持 5-10 秒",
    instructions: [
      "坐在椅子上，双脚踩地，患侧脚可穿袜子踩在光滑地面或滑板上",
      "主动把患侧足跟向椅子下方拉，让膝关节尽量弯曲，感觉大腿后侧在发力",
      "到最大角度后保持 5-10 秒，可用健侧脚背轻压患侧脚背再多弯一点",
      "缓慢回到起始位，每一次都尝试比上一次多弯一点点",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "屈膝时出现交锁、卡顿或打软，停止并就医",
      "半月板缝合术后早期须遵医嘱的屈膝角度上限",
    ],
    progressionCriteria: [
      "主动屈膝角度每周有进展，或已达到与健侧相差 10 度以内",
      "屈膝过程中无明显疼痛与卡顿",
    ],
    tags: ["膝盖", "屈膝角度", "主动活动"],
  },

  // ---------------------------------------------------------------------------
  // 力量
  // ---------------------------------------------------------------------------
  {
    id: "action_wall_sit",
    title: "靠墙静蹲",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 30 秒，组间休息 60 秒",
    instructions: [
      "背靠墙站立，双脚与肩同宽、向前迈出约一个半脚掌的距离",
      "沿墙面缓慢下滑到屈膝 30-60 度（初期不要超过 60 度），膝盖不超过脚尖",
      "膝盖对准第二脚趾方向，不要内扣；重量均匀分布在两脚全掌",
      "保持 30 秒，感觉大腿前侧持续酸胀发热，正常呼吸不憋气",
      "缓慢沿墙起身，休息 60 秒再做下一组",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝前（髌股关节）疼痛在屈膝加深时加重，则减小下蹲角度",
      "术后负重限制未解除前不做双腿或单腿静蹲",
    ],
    progressionCriteria: [
      "可无痛保持 60 秒",
      "能加深到屈膝 60 度或过渡到单腿静蹲仍保持膝盖不内扣",
    ],
    tags: ["膝盖", "等长", "闭链", "股四头肌"],
  },
  {
    id: "action_mini_squat",
    title: "微蹲",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 12 次，下蹲 3 秒 / 起身 2 秒",
    instructions: [
      "双脚与髋同宽站立，双手可轻扶椅背保持平衡",
      "髋部先向后坐，同时屈膝下蹲到约 30-45 度（浅蹲即可），躯干略前倾",
      "全程膝盖对准第二脚趾、不向内塌，重量均匀落在两脚（不要把重心偷到健侧）",
      "用 2 秒起身并夹紧臀部回到站立位，起身时不要膝盖锁死顶住",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "下蹲时膝盖内扣无法纠正，先退回臀桥与蚌式加强臀中肌",
      "术后负重限制未解除前不做",
    ],
    progressionCriteria: [
      "3 组 x 12 次无痛完成，且不需要扶手",
      "两侧受力对称（可用两个体重秤检查左右差 < 10%）",
    ],
    tags: ["膝盖", "闭链", "下蹲", "力量"],
  },
  {
    id: "action_sit_to_stand",
    title: "坐起站立",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 10 次，起身 2 秒 / 坐下 3 秒",
    instructions: [
      "坐在稳固的椅子前缘，双脚与髋同宽踩地，脚跟略在膝盖后方",
      "双手抱胸（力量不足时可扶扶手），躯干前倾把鼻尖送过脚尖",
      "两腿均匀用力蹬地站起，感觉大腿前侧和臀部同时发力，膝盖不内扣",
      "用 3 秒缓慢控制着坐回椅子，不要「砸」下去",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "站起时明显偏向健侧发力，先降低难度（垫高座椅）而不是硬做",
      "术后负重限制未解除前须遵医嘱",
    ],
    progressionCriteria: [
      "可在不用手的情况下完成 3 组 x 10 次",
      "能进阶到更矮的座椅或 30 秒内完成 12 次以上",
    ],
    tags: ["膝盖", "功能性", "闭链", "日常动作"],
  },
  {
    id: "action_terminal_knee_extension",
    title: "弹力带末端伸膝",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "strength",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 15 次，末端保持 2 秒",
    instructions: [
      "把弹力带一端固定在与膝同高的稳固物上，另一端套在患侧膝关节后方（腘窝处）",
      "面向固定点站立，向后退几步让弹力带有张力，患侧膝盖被带子拉成微屈约 30 度",
      "绷紧大腿前侧，主动把膝盖伸直对抗弹力带，脚跟保持踩地不移动",
      "末端伸直位保持 2 秒，感觉膝盖上方肌肉收紧，再用 3 秒缓慢让膝盖弯回 30 度",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "伸直末端出现膝关节过伸或不稳感时减小阻力",
      "术后负重限制未解除前改在坐位无负重下练伸膝",
    ],
    progressionCriteria: [
      "可用更强阻力的弹力带完成 3 组 x 15 次而无膝前痛",
      "步行时中间站立相不再出现膝关节打软或过伸",
    ],
    tags: ["膝盖", "伸膝", "弹力带", "闭链"],
  },
  {
    id: "action_leg_press_light",
    title: "轻负荷腿举",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 12 次，离心 3 秒 / 向心 2 秒，重量取 12 次能轻松完成的水平",
    instructions: [
      "坐进腿举机，双脚与髋同宽踩在踏板中部，脚跟踩实、膝盖对准脚尖方向",
      "调整活动范围：屈膝不超过 90 度（膝前痛者更浅），避免深屈膝下的大负荷",
      "用 2 秒把踏板推出，膝盖伸到接近直但不锁死",
      "用 3 秒缓慢收回，全程腰背贴紧靠背、脚跟不离板",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝前（髌股关节）痛者避免屈膝超过 90 度的大负荷推举",
      "术后负重限制未解除前禁用；ACL 术后早期先用双腿、暂不做单腿大负荷",
    ],
    progressionCriteria: [
      "同样重量下 3 组 x 12 次不再费力，且训练后 24 小时无肿胀反跳",
      "患侧单腿推举重量达到健侧的 80% 以上",
    ],
    tags: ["膝盖", "器械", "闭链", "渐进负荷"],
  },
  {
    id: "action_hamstring_curl",
    title: "俯卧腿弯举",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "strength",
    targetMuscles: ["腘绳肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "先徒手；加负荷前经许可：3 组 x 12 次，向心 2 秒 / 离心 3 秒",
    instructions: [
      "俯卧，双腿伸直并拢，髋部贴床，腹部微微收紧",
      "用 2 秒把患侧足跟向臀部方向弯举，弯到约 90 度，感觉大腿后侧收缩",
      "顶端停 1 秒，注意髋部不要抬起、臀部不要翘",
      "用 3 秒缓慢放回；踝部加沙袋或弹力带须先经医生/治疗师许可，不要自行加量",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "腘绳肌拉伤急性期或腘绳肌肌腱取腱（ACL 自体腘绳肌重建）术后早期，需经医生许可再做抗阻",
      "出现大腿后侧抽筋应停止、拉伸后再评估负荷",
    ],
    progressionCriteria: [
      "可加负荷完成 3 组 x 12 次且两侧力量接近对称",
      "俯卧抗阻屈膝时无牵扯痛；是否进阶到高强度离心（如北欧腿弯举）由治疗师评估后决定",
    ],
    tags: ["膝盖", "腘绳肌", "开链", "力量"],
  },
  {
    id: "action_romanian_deadlift",
    title: "单腿硬拉",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["腘绳肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 8 次（每侧），下放 3 秒 / 起身 2 秒",
    instructions: [
      "单腿站立（患侧支撑），支撑腿膝关节保持微屈约 15 度并全程锁定这个角度",
      "髋部向后推、躯干随之前倾，另一条腿向后伸出与躯干成一条直线",
      "下放过程中感觉支撑腿大腿后侧被拉紧、腰背保持挺直不弓背",
      "髋部前推、夹紧臀部起身回到站立位；熟练后可手持哑铃逐步加重",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "腘绳肌急性拉伤期不做负重版本",
      "腰部出现挤压痛或弓背无法纠正时，先徒手练习髋铰链",
      "平衡不足者先扶墙完成，避免跌倒",
    ],
    progressionCriteria: [
      "可徒手完成 3 组 x 8 次且骨盆不侧倾、无需扶手",
      "能手持负荷完成且患侧与健侧动作质量一致",
    ],
    tags: ["膝盖", "髋铰链", "腘绳肌", "单腿"],
  },
  {
    id: "action_clamshell",
    title: "蚌式开合",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["臀中肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 15 次（每侧），顶端保持 2 秒",
    instructions: [
      "侧卧，患侧在上，双膝屈曲约 45 度、双脚跟并拢，髋部与肩在一条垂线上",
      "保持双脚跟始终接触，把上方膝盖像蚌壳一样向上打开",
      "关键：骨盆不能向后翻，感觉应集中在臀部外侧（口袋位置）而不是大腿前侧或腰",
      "顶端保持 2 秒，用 3 秒缓慢合回；进阶可在膝上方套弹力圈",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "髋外侧疼痛（大转子滑囊/臀肌腱病）加重时减小幅度或减去弹力圈",
      "出现腰部代偿性酸痛说明骨盆在转动，先纠正姿势",
    ],
    progressionCriteria: [
      "可用弹力圈完成 3 组 x 15 次且骨盆稳定不后翻",
      "单腿站立与下蹲时膝盖内扣减少",
    ],
    tags: ["膝盖", "臀中肌", "髋外展", "膝内扣"],
  },
  {
    id: "action_side_lying_abduction",
    title: "侧卧髋外展",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["臀中肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 15 次（每侧），抬起后保持 2 秒",
    instructions: [
      "侧卧，患侧在上，双腿伸直叠放，身体贴着墙面有助于保持不前后晃",
      "上方腿保持伸直、脚尖朝前（不要外旋朝天花板），足跟略向后",
      "用臀部外侧把腿抬高约 30-40 度，感觉在臀部外侧而不是大腿外侧或腰",
      "顶端保持 2 秒，用 3 秒缓慢放下，不要让腿砸落",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "抬腿时腰侧代偿性发酸，说明抬得过高，降低幅度",
      "髋外侧腱病急性期减少组数或改为等长维持",
    ],
    progressionCriteria: [
      "可在踝部加沙袋或弹力带完成 3 组 x 15 次",
      "单腿站立时骨盆不下沉（无 Trendelenburg 征）",
    ],
    tags: ["膝盖", "臀中肌", "髋外展", "髋稳定"],
  },
  {
    id: "action_monster_walk",
    title: "弹力带侧向行走",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["臀中肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 每方向 10-12 步，组间休息 60 秒",
    instructions: [
      "把弹力圈套在双侧膝盖上方（进阶可下移到踝部），双脚与肩同宽",
      "屈髋屈膝呈半蹲位，躯干略前倾、重心压低并保持不变",
      "向侧方迈步，主动把膝盖顶开对抗弹力带，落地后另一只脚跟上但不要并拢",
      "全程膝盖不内扣、骨盆保持水平，臀部外侧应有明显灼热感",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "半蹲位引发膝前痛时抬高身位、减小屈膝角度",
      "术后负重限制未解除前不做",
    ],
    progressionCriteria: [
      "可用更强弹力圈或把带子下移到踝部完成 3 组而膝盖不内扣",
      "跑步或落地时膝内扣（外翻）明显减少",
    ],
    tags: ["膝盖", "臀中肌", "弹力带", "髋稳定"],
  },
  {
    id: "action_calf_raise",
    title: "提踵",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "strength",
    targetMuscles: ["小腿三头肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 15 次，抬起 2 秒 / 顶端 1 秒 / 下放 3 秒",
    instructions: [
      "站立，双手轻扶墙或椅背（只用于平衡，不借力）",
      "用 2 秒缓慢踮起脚跟到最高点，重心压在前脚掌第一二跖骨，脚踝不要向外翻",
      "顶端停 1 秒，感觉小腿后侧强烈收缩",
      "用 3 秒缓慢落回地面；进阶为单腿提踵或站在台阶边缘增大活动范围",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跟腱急性疼痛或跟腱术后早期须遵医嘱",
      "术后负重限制未解除前不做单腿版本",
    ],
    progressionCriteria: [
      "单腿可连续完成 20 次以上且高度不衰减",
      "患侧与健侧的单腿提踵次数差 < 20%",
    ],
    tags: ["膝盖", "小腿", "推蹬", "回归跑步准备"],
  },
  {
    id: "action_step_up",
    title: "上台阶",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 10 次（每侧），从 10-15 厘米台阶起步",
    instructions: [
      "面对稳固的台阶站立，患侧整只脚踩上台阶，膝盖对准第二脚趾",
      "用患侧腿蹬地把身体推上去，尽量不用后腿蹬地、不用手扶栏杆借力",
      "站上台阶时髋膝完全伸直、骨盆保持水平，不要向一侧塌",
      "用 3 秒控制着把后腿轻放回地面，落地要「无声」",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝盖内扣或骨盆下沉无法纠正时降低台阶高度",
      "术后负重限制未解除前不做",
    ],
    progressionCriteria: [
      "可在 20 厘米台阶上完成 3 组 x 10 次，动作无膝内扣",
      "能手持负荷或提高台阶高度且落地依然可控",
    ],
    tags: ["膝盖", "单腿", "功能性", "闭链"],
  },
  {
    id: "action_split_squat",
    title: "分腿蹲",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "strength",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 8-10 次（每侧），下蹲 3 秒 / 起身 2 秒",
    instructions: [
      "前后分腿站立，患侧在前，两脚间距约一大步，躯干保持直立",
      "身体垂直下沉，后侧膝盖朝地面靠近（不必触地），前腿屈膝约 90 度",
      "前腿膝盖对准第二脚趾、不内扣，重心主要压在前脚全掌",
      "用前腿蹬地起身，感觉前侧大腿与臀部发力；平衡不足时手扶墙",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝前痛者减小下蹲深度，先不做后脚抬高的保加利亚版本",
      "术后负重限制或屈膝角度限制未解除前不做",
    ],
    progressionCriteria: [
      "可徒手完成 3 组 x 10 次且无需扶手、膝盖不内扣",
      "能手持负荷或进阶到后脚抬高版本",
    ],
    tags: ["膝盖", "单腿", "下肢力量", "闭链"],
  },
  {
    id: "action_plank",
    title: "平板支撑",
    bodyRegion: "knee",
    bodyRegions: ["knee", "spine"],
    actionType: "strength",
    targetMuscles: ["核心肌群"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 30 秒，组间休息 45 秒",
    instructions: [
      "俯卧撑姿，前臂着地，肘关节在肩正下方，双脚与髋同宽",
      "收紧腹部与臀部，把骨盆略后倾，让头、肩、髋、踝成一条直线",
      "正确的感觉是腹部持续绷紧发热；如果腰部发酸下塌，说明骨盆没收好",
      "保持 30 秒，正常呼吸；力量不足时先做屈膝跪姿版本",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "跪姿版本会压迫膝前，膝前痛或膝前有未愈切口者改用标准版或前臂+脚尖支撑",
      "出现腰部挤压痛立即停止并降低难度",
    ],
    progressionCriteria: [
      "可保持 60 秒且腰部不塌陷",
      "能进阶到单腿抬起版本仍保持骨盆水平",
    ],
    tags: ["膝盖", "核心", "躯干稳定"],
  },
  {
    id: "action_side_plank",
    title: "侧平板支撑",
    bodyRegion: "knee",
    bodyRegions: ["knee", "spine", "hip"],
    actionType: "strength",
    targetMuscles: ["核心肌群", "臀中肌"],
    source: "seed",
    phase: "力量",
    defaultDosage: "3 组 x 20-30 秒（每侧）",
    instructions: [
      "侧卧，前臂着地、肘在肩正下方，双腿伸直叠放（初期可屈膝以膝支撑）",
      "收紧腹部和臀部，把髋部抬离地面，让头、髋、踝成一条直线",
      "正确的感觉是下侧腰腹外侧和上侧臀部外侧同时发力，身体不前后晃",
      "保持 20-30 秒后缓慢放下，换边",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "屈膝支撑版本会压到膝外侧，膝外侧痛者改用足部支撑",
      "肩部疼痛者改为侧卧髋外展替代",
    ],
    progressionCriteria: [
      "两侧均可保持 45 秒且髋部不下沉",
      "能进阶到上方腿抬起（侧支撑+外展）",
    ],
    tags: ["膝盖", "核心", "臀中肌", "侧向稳定"],
  },

  // ---------------------------------------------------------------------------
  // 神经肌肉控制
  // ---------------------------------------------------------------------------
  {
    id: "action_single_leg_stand",
    title: "单腿站立",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "balance",
    targetMuscles: ["股四头肌", "臀中肌"],
    source: "seed",
    phase: "神经肌肉控制",
    defaultDosage: "3 组 x 30 秒（每侧），组间休息 30 秒",
    instructions: [
      "站在稳固的平地上，旁边有墙或椅背可随时扶（先不扶）",
      "抬起健侧腿，患侧单腿支撑，支撑腿膝关节保持微屈、不要锁死",
      "骨盆保持水平（不要一侧塌下去），膝盖对准第二脚趾、不内扣",
      "眼睛看向前方固定一点，保持 30 秒；脚趾会有细微调整是正常的",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "有跌倒风险或明显打软感时，必须在扶手旁进行",
      "术后单腿负重许可未下达前不做",
    ],
    progressionCriteria: [
      "可稳定保持 30 秒不落脚、不扶手",
      "骨盆保持水平且膝盖不内扣，可进阶到闭眼或软垫上",
    ],
    tags: ["膝盖", "平衡", "本体感觉", "单腿"],
  },
  {
    id: "action_single_leg_stand_eyes_closed",
    title: "闭眼单腿站立",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "balance",
    targetMuscles: ["股四头肌", "臀中肌"],
    source: "seed",
    phase: "神经肌肉控制",
    defaultDosage: "3 组 x 15-20 秒（每侧）",
    instructions: [
      "先确认睁眼单腿站立能稳定保持 30 秒，再做本动作",
      "站在墙角或有扶手的地方，双手悬在扶手上方随时可抓",
      "单腿站立后缓慢闭眼，靠脚踝与髋的细微调整维持平衡",
      "保持 15-20 秒；一旦落脚或需要抓扶手，睁眼重新开始",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "睁眼单腿站立还站不稳、或有眩晕/前庭疾病者不做",
      "必须在有支撑物的环境进行，避免跌倒",
    ],
    progressionCriteria: [
      "闭眼可稳定保持 20 秒不落脚",
      "可进阶到闭眼站在软垫或平衡垫上",
    ],
    tags: ["膝盖", "平衡", "本体感觉", "进阶"],
  },
  {
    id: "action_step_down_control",
    title: "台阶控制下落",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "balance",
    targetMuscles: ["股四头肌", "臀大肌"],
    source: "seed",
    phase: "神经肌肉控制",
    defaultDosage: "3 组 x 8-10 次（每侧），下落全程 3-4 秒",
    instructions: [
      "患侧腿单脚站在 10-15 厘米台阶上，健侧腿悬在台阶前方",
      "髋部向后坐，患侧腿缓慢屈膝，让健侧脚跟轻点地面（不要把重量交出去）",
      "全程用患侧腿控制速度，膝盖对准第二脚趾、不内扣，骨盆保持水平",
      "轻点地后用患侧腿把身体推回站直；落地必须无声，若「砸」下去说明高度太大",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "膝前（髌股关节）痛在离心下落时加重，则降低台阶高度",
      "膝盖内扣或明显打软时停止，退回双腿闭链训练",
    ],
    progressionCriteria: [
      "可在 20 厘米台阶上完成 3 组 x 10 次，全程无膝内扣、落地无声",
      "患侧与健侧动作质量与速度对称",
    ],
    tags: ["膝盖", "离心控制", "单腿", "下楼准备"],
  },
  {
    id: "action_y_balance",
    title: "Y 字平衡触地",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "balance",
    targetMuscles: ["股四头肌", "臀中肌"],
    source: "seed",
    phase: "神经肌肉控制",
    defaultDosage: "3 组 x 每方向 5 次（每侧）",
    instructions: [
      "患侧单腿站立，双手叉腰，支撑腿膝关节微屈",
      "用健侧脚依次向前方、后内侧、后外侧三个方向尽量远地伸出，脚尖轻点地面即收回",
      "触地时只是「轻点」，不把重量转移过去；支撑腿膝盖始终对准第二脚趾不内扣",
      "全程躯干保持直立、骨盆水平，失去平衡就缩短伸出距离",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "单腿站立尚不能稳定保持 30 秒者先退回单腿站立",
      "支撑腿出现打软或膝盖内扣立即停止",
    ],
    progressionCriteria: [
      "三个方向的触地距离患侧达到健侧的 90% 以上",
      "全程无失衡、无膝内扣",
    ],
    tags: ["膝盖", "平衡", "动态稳定", "评估动作"],
  },
  {
    id: "action_single_leg_rdl_balance",
    title: "单腿平衡前伸",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "balance",
    targetMuscles: ["腘绳肌", "臀大肌"],
    source: "seed",
    phase: "神经肌肉控制",
    defaultDosage: "3 组 x 8 次（每侧），下放 3 秒 / 起身 2 秒",
    instructions: [
      "患侧单腿站立，支撑腿膝关节保持微屈约 15 度",
      "髋部向后推、躯干缓慢前倾，另一条腿向后伸直，躯干与后腿成一条直线",
      "感觉支撑腿大腿后侧被拉紧、臀部在控制身体，膝盖不内扣、骨盆不侧翻",
      "前倾到躯干接近水平（或可控范围）后，用臀部把身体带回直立位",
      "熟练后可在前伸终点用手轻触地面上的目标物，增加控制难度",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "腘绳肌急性拉伤期不做",
      "平衡不足者先扶墙练习，避免跌倒",
    ],
    progressionCriteria: [
      "可不扶手完成 3 组 x 8 次且骨盆全程保持水平",
      "能在前伸终点稳定触地并顺利返回",
    ],
    tags: ["膝盖", "平衡", "髋铰链", "腘绳肌"],
  },

  // ---------------------------------------------------------------------------
  // 回归活动
  // ---------------------------------------------------------------------------
  {
    id: "action_stair_descent",
    title: "下台阶控制",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "strength",
    targetMuscles: ["股四头肌"],
    source: "seed",
    phase: "回归活动",
    defaultDosage: "3 组 x 10 级台阶，每级下落控制 2-3 秒",
    instructions: [
      "站在楼梯顶端，手轻扶栏杆（只作保护，不借力）",
      "患侧腿先下一级，用患侧的大腿前侧控制身体缓慢下降，落地时脚掌轻放不发出声响",
      "身体保持正对前方，膝盖对准第二脚趾、不内扣，骨盆保持水平",
      "逐级下行 10 级；感觉大腿前侧持续在「刹车」而不是靠身体砸下去",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "下楼时出现膝前痛或髌骨摩擦痛加重，退回台阶控制下落并降低高度",
      "出现打软或不稳感时停止，扶栏杆下楼",
    ],
    progressionCriteria: [
      "可交替腿正常下楼、无需扶栏杆且无膝前痛",
      "训练后 24 小时无肿胀与疼痛反跳",
    ],
    tags: ["膝盖", "离心控制", "日常功能", "下楼"],
  },
  {
    id: "action_walk_jog_intervals",
    title: "走跑交替",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "conditioning",
    targetMuscles: ["股四头肌", "小腿三头肌"],
    source: "seed",
    phase: "回归活动",
    defaultDosage: "跑 1 分钟 / 走 2 分钟 x 6-8 轮，隔天一次，总时长约 20-25 分钟",
    instructions: [
      "先做 5 分钟快走热身，确认无痛、无跛行再开始",
      "在平整路面上慢跑 1 分钟，步频略快、步幅小，落地轻、脚步声小",
      "转为快走 2 分钟主动恢复，重复 6-8 轮后再快走 5 分钟放松",
      "任何一轮出现跛行、膝痛或打软，立刻改为全程步行并结束本次训练",
      "每周跑走比例的增加不超过 10%，两次训练之间至少间隔一天",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "训练后 24 小时内出现肿胀、疼痛加重或跛行，则回退到上一周的量",
      "未达到回归跑步标准（单腿提踵 20 次、单腿蹲无痛、无肿胀）前不要开始",
    ],
    progressionCriteria: [
      "可无痛完成且训练后 24 小时无肿胀与疼痛反跳",
      "能连续慢跑 10 分钟不跛行，再进入持续跑",
    ],
    tags: ["膝盖", "回归跑步", "渐进负荷", "有氧"],
  },
  {
    id: "action_forward_hop",
    title: "向前单腿跳",
    bodyRegion: "knee",
    bodyRegions: ["knee", "ankle_foot"],
    actionType: "plyometric",
    targetMuscles: ["股四头肌", "小腿三头肌"],
    source: "seed",
    phase: "回归活动",
    defaultDosage: "3 组 x 5 次（每侧），每次落地稳定 2 秒后再做下一次",
    instructions: [
      "患侧单腿站立，双臂自然摆动辅助发力，屈髋屈膝下蹲蓄力",
      "向前单腿跳出一个可控的距离（初期短一点，能稳稳落住为准）",
      "用同一条腿落地：前脚掌先着地、屈膝屈髋缓冲，落地要轻、无声",
      "落地后保持平衡站稳 2 秒，膝盖对准第二脚趾、不内扣，再进行下一次",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "落地时膝盖内扣、打软或无法站稳 2 秒，说明尚未达到跳跃阶段，退回台阶控制下落",
      "关节仍有肿胀、或患侧力量不足健侧 80% 时不做跳跃",
      "训练后 24 小时出现肿胀反跳则暂停跳跃训练",
    ],
    progressionCriteria: [
      "单腿跳远距离达到健侧的 90% 以上且落地可控",
      "连续 5 次落地均无膝内扣、无失衡",
    ],
    tags: ["膝盖", "跳跃", "落地控制", "回归运动"],
  },
  {
    id: "action_lateral_hop",
    title: "侧向单腿跳",
    bodyRegion: "knee",
    bodyRegions: ["knee", "hip"],
    actionType: "plyometric",
    targetMuscles: ["臀中肌", "股四头肌"],
    source: "seed",
    phase: "回归活动",
    defaultDosage: "3 组 x 每侧 6-8 次，落地稳定 2 秒后再跳回",
    instructions: [
      "地面上放一条胶带或一根低矮标志线，患侧单腿站在线的一侧",
      "向侧方跳过线，用同一条腿落地，前脚掌先着地并屈膝缓冲",
      "落地后稳定 2 秒：膝盖不能向内塌、骨盆保持水平、上身不要甩向一边",
      "站稳后再跳回起始侧；先追求落地质量，再逐步加距离和速度",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "落地出现膝内扣或打软立即停止，回到弹力带侧向行走与单腿控制训练",
      "关节肿胀未消退、或向前单腿跳尚未达标时不做侧向跳",
    ],
    progressionCriteria: [
      "侧向跳距离与稳定性达到健侧的 90% 以上",
      "可连续跳跃（不停顿）且全程膝盖不内扣",
    ],
    tags: ["膝盖", "侧向", "跳跃", "回归运动"],
  },
  {
    // 高强度离心，ACL 自体腘绳肌腱重建术后早中期禁用。
    // 模型在选动作时只看得到 `id: 标题；类型；目标肌群；阶段；剂量` 这一行，
    // contraindications 是选完之后才展示给病人的——所以把关必须写进标题/阶段/剂量里，
    // 否则病人一句「大腿后侧紧」就能靠 TF-IDF 把这条捞上菜单。
    id: "action_nordic_eccentric",
    title: "北欧腿弯举（进阶，需治疗师许可）",
    bodyRegion: "knee",
    bodyRegions: ["knee"],
    actionType: "strength",
    targetMuscles: ["腘绳肌"],
    source: "seed",
    phase: "回归活动",
    defaultDosage: "须经治疗师许可后再做：2-3 组 x 4-6 次（每周 1-2 次），下落全程控制 3-5 秒",
    instructions: [
      "跪在软垫上，躯干与大腿成一条直线，请同伴牢牢压住双侧脚踝（或用固定器）",
      "保持髋部不折叠、臀部收紧，用大腿后侧的力量控制身体缓慢向前倒",
      "尽量把「还能刹住」的角度往下延伸，感觉大腿后侧强烈拉紧",
      "控制不住时双手撑地缓冲，再用手臂推起回到起始位（起身不靠腘绳肌）",
      "初期只做很小的下落幅度，能全程控制多少就做多少，逐周增加",
    ],
    contraindications: [
      "训练中疼痛超过 4/10 立即停止",
      "这是高强度离心动作：腘绳肌拉伤未完全康复、或 ACL 自体腘绳肌腱重建术后早中期禁用，须经医生/治疗师许可",
      "跪位膝前受压疼痛或膝关节屈曲受限者不做",
      "训练后 48 小时内明显延迟性酸痛导致跛行，说明量过大，下次减半",
    ],
    progressionCriteria: [
      "可在无痛下控制下落到水平位以下并保持动作不「折髋」",
      "训练后 48 小时酸痛可耐受、不影响行走与既有跑步量",
    ],
    tags: ["膝盖", "腘绳肌", "离心", "进阶", "需治疗师许可"],
  },
];
